### ISSUE TITLE
When should the Julia BMI return something

### ISSUE THREAD

**Issue by BSchilperoort** [csdms/bmi-example-julia#8]
Many functions in the implementation here return values. For example:
- BMI.update
- BMI.finalize
- BMI.set_value

all return the model struct. Same for the Wflow.jl implementation.

However, this returns are not in the specification: https://github.com/Deltares/BasicModelInterface.jl

Working on [remotebmi](https://github.com/eWaterCycle/remotebmi) we encountered this inconsistency between the specification and the implementations.

So we wonder which one is valid:
```jl
function update(m::Model)::Model
    m.current+= 1
    m
end
```
or 
```jl
function update(m::Model)::Nothing
    m.current+= 1
    return nothing
end
```
<hr>

And why would this:
```jl
m = update(m)
```
be preferable to
```jl
update(m)
```

**Comment by BSchilperoort** [comment]
If this issue is more related to https://github.com/Deltares/BasicModelInterface.jl I could open the issue there instead.

**Comment by visr** [comment]
Hmm, so am I correct that the BMI doesn't specify this, and neither does BasicModelInterface.jl? That would mean both are valid.

I guess only in the case where your `Model` object is fully immutable, where for some reason you construct a new `Model` on `update`, because you cannot rely on side-effects. That would require you to return the Model and use `m = update(m)`. But I don't think this is likely in practice, so perhaps we should suggest returning `nothing` instead. In any case I'd recommend `update(m)` over `m = update(m)` to avoid relying on the model being returned.

I'd be happy to accept PRs that clarify this or start returning nothing.

**Comment by BSchilperoort** [comment]
> BMI doesn't specify this

The [BMI SIDL specifies](https://bmi.readthedocs.io/en/stable/#update) that these kinds of functions would return an integer: this is just to allow for C and Fortran implementations to return an error code. However, in the C++, Java and Python implementations the functions should return `void`/`None` as exceptions will be raised on an error.

> the BMI doesn't specify this, and neither does BasicModelInterface.jl? That would mean both are valid.

I would think that if the BMI and BasicModelInterface.jl don't specify that the functions should return anything, that they then shouldn't return anything. But this is not explicitly stated.

@mdpiper @mcflugen any opinions? If everyone agrees I can make a PR here and in BasicModelInterface.jl to start returning `nothing` at the end of these functions.

**Comment by mdpiper** [comment]
@BSchilperoort I agree with what you wrote in https://github.com/Deltares/BasicModelInterface.jl/issues/3: BMI aims to be developer-friendly, and a BMI should use the lowest-level language constructs possible that are still natural in a language. I don't know Julia well (yet!), so I can't offer an opinion on what those constructs should be.

**Comment by visr** [comment]
Thanks. So let's go ahead with suggesting to `return nothing`. Either way is natural to Julia, so let's err on the side of cross-language consistency.

@BSchilperoort in Julia you can also define C callable functions, so here we do return Int32 since then it becomes a valid BMI C API: https://github.com/Deltares/Ribasim/blob/v2024.11.0/core/src/libribasim.jl. But those functions live outside the BasicModelInterface.jl module.

**Comment by BSchilperoort** [comment]
OK, I'll make a PR here and in BasicModelInterface.jl

> @BSchilperoort in Julia you can also define C callable functions, so here we do return Int32 since then it becomes a valid BMI C API: https://github.com/Deltares/Ribasim/blob/v2024.11.0/core/src/libribasim.jl. But those functions live outside the BasicModelInterface.jl module.

In that case throwing an error in Julia would seem better to me that to pass on an error code :thinking:

**Comment by visr** [comment]
It's not really Julia anymore at that point though right? We do print the julia error, but have to return an Int32. These functions are not meant to be called from Julia, but baked into a DLL with [PackageCompiler.jl](https://julialang.github.io/PackageCompiler.jl/dev/refs.html#PackageCompiler.create_library).

**Comment by BSchilperoort** [comment]
> It's not really Julia anymore at that point though right? We do print the julia error, but have to return an Int32. These functions are not meant to be called from Julia, but baked into a DLL with [PackageCompiler.jl](https://julialang.github.io/PackageCompiler.jl/dev/refs.html#PackageCompiler.create_library).

OK, I misunderstood that!
